### ISSUE TITLE
Display all translations for a specific string

### ISSUE THREAD

**Issue by grappler** [GlotPress/GlotPress-standalone#5]
When discussing making changes to strings it would be interesting to be able to see all of the translations for the specific string.

A specific example would be the string change in [#core-38545](https://core.trac.wordpress.org/ticket/38545) where `Archives: %s` is being changed to `Archives:`.

translate.wp.com already has this feature: https://translate.wordpress.com/projects/wpcom/-all-translated/171842/

**Comment by pedro-mendonca** [comment]
Hi @grappler,
You should use the current development repo: https://github.com/GlotPress/GlotPress-WP

**Comment by grappler** [comment]
done https://github.com/GlotPress/GlotPress-WP/issues/822
