### ISSUE TITLE
Keyboard shortcuts on laptops

### ISSUE THREAD

**Issue by claudiosanches** [GlotPress/GlotPress-standalone#6]
Some shortcuts like `Ctrl +` and `Ctrl -` does not work when not using a numeric keyboard, like in small laptops. Generally does not work when comes in keys like `+=` and `_-`.

**Comment by toolstack** [comment]
You probably want to open this in the GlotPress-WP repo.  This issue tracker is for the old standalone GP which is no longer supported.

**Comment by claudiosanches** [comment]
Ohh, sorry.
